---
driver:
  name: docker
  use_sudo: false
  privileged: true
  run_command: /usr/sbin/init
  provision_command:
    - yum -y swap -- remove systemd-container systemd-container-libs -- install systemd
    - systemctl enable sshd.service

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.2
    driver:
      image: 'phazyy/kitchen-docker:0.1.0'

suites:
  - name: default
    run_list:
      - recipe[adam-vagrant::yum_repos]
      - recipe[adam-vagrant::common]
      - recipe[adam-vagrant::chefdk]
      # - recipe[adam-vagrant::docker]
      - recipe[adam-vagrant::zsh]
      - recipe[adam-vagrant::vim]
      - recipe[adam-vagrant::java]
      - recipe[adam-vagrant::sublime_text]
    attributes:
      vagrant:
        user: 'kitchen'
        vm_type: 'headed'
      oh-my-zsh:
        theme: 'pure'
        plugins: ['git', 'sudo']
      git:
        name: 'kitchen-user'
        email: 'kitchen@chef.io'
