---

- name: Install dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - ca-certificates
    - yum-utils

- name: Download docker install script
  get_url:
    url: "{{ docker_install_script }}"
    dest: "/tmp/install-docker.sh"
    mode: 0755



- name: Execute docker install script
  shell: "/tmp/install-docker.sh"
