---

- name: Install zsh package
  yum:
    name: zsh
    state: present

# Following needs to be ran as the vagrant user
- name: Download oh-my-zsh install script
  get_url:
    url: "{{ omz_install_script }}"
    dest: /home/vagrant/oh-my-zsh.sh
    mode: 0755

- name: Execute oh-my-zsh script
  environment:
    SHELL: /usr/bin/zsh
    HOME: /home/vagrant
  shell: "/home/vagrant/oh-my-zsh.sh"

- name: Create zsh config file
  template:
    src: .zshrc
    dest: /home/vagrant/.zshrc
    owner: vagrant
    mode: 644
