---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  # TODO : Find / create a docker image with chef-omnibus installed
  # https://github.com/zuazo/chef-local-docker

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      #- recipe[adam-vagrant::yum_repos]
      #- recipe[adam-vagrant::dev_tools]
      - recipe[adam-vagrant::dev_chef]
    attributes:
      dev_tools:
        vm_type: 'headless'
      vagrant:
        user: 'kitchen'
