---
- hosts: all
  become: true
  become_user: root
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/setup.yml
    - include: tasks/docker.yml
    - include: tasks/java.yml
    - include: tasks/zsh.yml
