---
- hosts: all
  become: yes

  vars:
    x_ansible_download_dir: /usr/local/src/ansible/data

  roles:
    - role: geerlingguy.ntp
      ntp_timezone: Europe/London

    - role: gantsign.inotify
      inotify_max_user_watches: 524288

    - role: gantsign.keyboard
      keyboard_model: pc105
      keyboard_layout: gb

    - role: geerlingguy.git

    - role: gantsign.git_user
      users:
        - username: vagrant
          git_user_name: '{{ git_user_name | default(None) }}'
          git_user_email: '{{ git_user_email | default(None) }}'
          git_user_force: '{{ git_user_force | default(False) }}'

    - role: viasite-ansible.zsh
      tags:
        - zsh
      zsh_aliases:
        - alias: dsh
          action: 'docker exec -it "$@" /bin/sh'
        - alias: dps
          action: 'docker ps "$@" --format {%raw%}"{{.ID}}\t{{.Status}}\t{{.Image}}\t"{%endraw%}'
      zsh_antigen_bundles:
        - git
        - docker
        - command-not-found
        - zsh-users/zsh-autosuggestions
        - zdharma/fast-syntax-highlighting
        - chrissicool/zsh-256color
        - urbainvaes/fzf-marks
        - ytet5uy4/fzf-widgets
        - wfxr/forgit
      zsh_antigen_theme: robbyrussell
      zsh_fzf_height: "30%"
      zsh_user: vagrant

    - role: geerlingguy.docker
      tags:
        - docker
      docker_users:
        - vagrant

    # Install Kubernetes - Needs work, fails on Flannel networking setup.
    # See: https://github.com/geerlingguy/ansible-role-kubernetes/issues/30
    # - role: geerlingguy.kubernetes
    #   tags:
    #     - kubernetes
    #     - docker
    #   kubernetes_node_type: master
    #   kubernetes_allow_pods_on_master: true
    #   kubernetes_pod_network_cidr: 10.244.0.0/16
    #   kubernetes_version: '1.11'

    - role: gantsign.minikube
      tags:
        - kubernetes
        - docker

    - role: gantsign.helm
      tags:
        - kubernetes
        - docker

    - role: gantsign.kompose
      tags:
        - kubernetes
        - docker

    - role: gantsign.kops
      tags:
        - kubernetes
        - docker

    - role: gantsign.java
      tags:
        - java
      java_fact_group_name: java_8
      java_install_dir: '{{ java_install_dir }}'
      java_is_default_installation: no
      java_version: 8u192

    - role: gantsign.maven
      tags:
        - java
        - maven
      maven_install_dir: '{{ maven_install_dir }}'
      maven_version: '3.6.0'
      gather_timeout: 20

    - role: gantsign.golang
      tags:
        - golang
      golang_gopath: '$HOME/workspace-go'

    - role: weareinteractive.environment
      environment_config:
        CDPATH: ".:/home/vagrant/workspace:/home/vagrant/workspace-go/src/github.com/gantsign"
        TREE_COLORS: ':no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.bat=01;32:*.BAT=01;32:*.btm=01;32:*.BTM=01;32:*.cmd=01;32:*.CMD=01;32:*.com=01;32:*.COM=01;32:*.dll=01;32:*.DLL=01;32:*.exe=01;32:*.EXE=01;32:*.arj=01;31:*.bz2=01;31:*.deb=01;31:*.gz=01;31:*.lzh=01;31:*.rpm=01;31:*.tar=01;31:*.taz=01;31:*.tb2=01;31:*.tbz2=01;31:*.tbz=01;31:*.tgz=01;31:*.tz2=01;31:*.z=01;31:*.Z=01;31:*.zip=01;31:*.ZIP=01;31:*.zoo=01;31:*.asf=01;35:*.ASF=01;35:*.avi=01;35:*.AVI=01;35:*.bmp=01;35:*.BMP=01;35:*.flac=01;35:*.FLAC=01;35:*.gif=01;35:*.GIF=01;35:*.jpg=01;35:*.JPG=01;35:*.jpeg=01;35:*.JPEG=01;35:*.m2a=01;35:*.M2a=01;35:*.m2v=01;35:*.M2V=01;35:*.mov=01;35:*.MOV=01;35:*.mp3=01;35:*.MP3=01;35:*.mpeg=01;35:*.MPEG=01;35:*.mpg=01;35:*.MPG=01;35:*.ogg=01;35:*.OGG=01;35:*.ppm=01;35:*.rm=01;35:*.RM=01;35:*.tga=01;35:*.TGA=01;35:*.tif=01;35:*.TIF=01;35:*.wav=01;35:*.WAV=01;35:*.wmv=01;35:*.WMV=01;35:*.xbm=01;35:*.xpm=01;35:'

    - role: weareinteractive.environment
      tags:
        - java
      environment_config:
        JAVA_HOME: "{{ java_install_dir }}"
        M2_HOME: "{{ maven_install_dir }}"
        MAVEN_OPTS: '-XX:TieredStopAtLevel=1 -Xverify:none'
